=== nickyminch/xmlium/src/main/resources/xsd/TestConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

     xmlium-web, is an extension for selenium-java test framework allowing for tests
     to be described in xml files.

     The contents of this file are subject GNU Lesser General Public License
     Version 3 or later, you may not use this file except in compliance
     with the License.

     You may obtain a copy of the License at:
     https://www.gnu.org/licenses/lgpl.html

     Software distributed under the License is distributed on an "AS IS" basis,
     WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
     for the specific language governing rights and limitations under the
     License.

-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.xmlium.org/xsd/1.0/TestConfig" xmlns:tns="http://www.xmlium.org/xsd/1.0/TestConfig" elementFormDefault="qualified">
   
   	<element name="testConfig" type="tns:Config"/>
   	
    <complexType name="Config">
    	<sequence>
    		<element name="pathString" type="string" minOccurs="0" maxOccurs="1"/>
    		<element name="driverClass" type="string" maxOccurs="1"/>
    		<element name="appId" type="string" minOccurs="0" maxOccurs="1"/>
    		<element name="appApk" type="string" minOccurs="0" maxOccurs="1"/>
    		<element name="timeout" type="long" maxOccurs="1"/>
    		<element name="timeUnit" type="string" maxOccurs="1"/>
    		<element name="url" type="string" minOccurs="0" maxOccurs="1"/>
    		<element name="fluentWaitIgnore" type="tns:FluentWaitIgnore" maxOccurs="1"/>
    		<element name="locale" type="string" maxOccurs="1"/>
    		<element name="delay" type="integer" maxOccurs="1"/>
    		<element name="unformat" type="boolean" minOccurs="0" maxOccurs="1"/>
    	</sequence>
    </complexType>
    <complexType name="FluentWaitIgnore">
    	<sequence>
    			<element name="exceptionClassNames" type="tns:FluentWaitExceptionsList"/>
    	</sequence>
    </complexType>

     <simpleType name="FluentWaitExceptionsList">
    		<list itemType="string"/>
    </simpleType>
</schema>

=== nickyminch/xmlium/src/test/resources/com/example/test/base/config2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testConfig [
<!ENTITY resourcesPathString  "../someproject/src/main/resources/de/worldportfolio">
<!ENTITY url  "http://localhost:8080/">
]>
<tns:testConfig xmlns:tns="http://www.xmlium.org/TestConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xmlium.org/TestConfig /src/main/xsd/TestConfig.xsd ">
     <tns:pathString>&resourcesPathString;</tns:pathString>
     <tns:driverClass>org.openqa.selenium.chrome.ChromeDriver</tns:driverClass>
     <tns:timeout>4</tns:timeout>
     <tns:timeUnit>SECONDS</tns:timeUnit>
     <tns:url>&url;</tns:url>
     <tns:locale>de_DE</tns:locale>
     <tns:fluentWaitIgnore>
       <tns:exceptionClassNames>
       	org.openqa.selenium.NoSuchElementException
       	org.openqa.selenium.StaleElementReferenceException
       </tns:exceptionClassNames>
     </tns:fluentWaitIgnore>
     <tns:delay>150</tns:delay>
</tns:testConfig>

=== nickyminch/xmlium/src/test/resources/com/example/test/base/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml [
<!ENTITY resourcesPathString  "path/to/your/resources">
<!ENTITY url  "http://localhost:8080/">
]>
<tns:testConfig xmlns:tns="http://www.xmlium.org/xsd/1.0/TestConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xmlium.org/xsd/1.0/TestConfig http://www.xmlium.org/xsd/1.0/TestConfig.xsd">
     <tns:pathString>&resourcesPathString;</tns:pathString>
     <!-- tns:driverClass>org.openqa.selenium.ie.InternetExplorerDriver</tns:driverClass -->
     <!-- tns:driverClass>org.openqa.selenium.firefox.FirefoxDriver</tns:driverClass -->
     <tns:driverClass>org.openqa.selenium.chrome.ChromeDriver</tns:driverClass>
     <tns:timeout>4</tns:timeout>
     <tns:timeUnit>SECONDS</tns:timeUnit>
     <tns:url>&url;</tns:url>
     <tns:fluentWaitIgnore>
       <tns:exceptionClassNames>
       	org.openqa.selenium.NoSuchElementException
       	org.openqa.selenium.StaleElementReferenceException
       </tns:exceptionClassNames>
     </tns:fluentWaitIgnore>
     <tns:locale>de_DE</tns:locale>
     <tns:delay>150</tns:delay>
     <!-- tns:delay>250</tns:delay -->
</tns:testConfig>

=== nickyminch/xmlium/src/test/resources/com/example/test/android/base/configAndroid.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:testConfig xmlns:tns="http://www.xmlium.org/TestConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xmlium.org/TestConfig http://www.xmlium.org/TestConfig.xsd">
     <!-- tns:driverClass>org.openqa.selenium.ie.InternetExplorerDriver</tns:driverClass -->
     <!-- tns:driverClass>org.openqa.selenium.firefox.FirefoxDriver</tns:driverClass -->
     <tns:driverClass>io.selendroid.client.SelendroidDriver</tns:driverClass>
     <tns:appId>io.selendroid.testapp:0.17.0</tns:appId>
     <tns:appApk>src/main/resources/selendroid-test-app-0.17.0.apk</tns:appApk>
     <tns:timeout>1</tns:timeout>
     <tns:timeUnit>SECONDS</tns:timeUnit>
     <tns:fluentWaitIgnore>
       <tns:exceptionClassNames>
       	org.openqa.selenium.NoSuchElementException
       	org.openqa.selenium.StaleElementReferenceException
       </tns:exceptionClassNames>
     </tns:fluentWaitIgnore>
     <tns:locale>de_DE</tns:locale>
     <tns:delay>150</tns:delay>
     <!-- tns:delay>250</tns:delay -->
</tns:testConfig>
