=== nickyminch/xmlium/src/main/xsd/TestCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TestCase" xmlns:tns="http://www.example.org/TestCase" elementFormDefault="qualified">
    <complexType name="Test">
    	<choice>
    		<element name="Steps" type="tns:StepType" maxOccurs="unbounded"></element>
    		<element name="repeat" type="tns:Repeat"/>
    	</choice>
    </complexType>

    <element name="test" type="tns:Test"></element>

	<complexType name="Repeat">
		<sequence>
			<element name="repeatCount" type="integer"/>
			<element name="Steps" type="tns:StepType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
    <complexType name="StepType">
    	<sequence>
	    	<choice maxOccurs="1" minOccurs="1">
	    		<element name="element" type="tns:Element"></element>
	    		<element name="select" type="tns:Select"></element>
	    		<element name="prettySelect" type="tns:PrettySelect"></element>
	    		<element name="switchTo" type="tns:SwitchTo"></element>
	    	</choice>
	    	<element name="load" type="tns:Load"  maxOccurs="1" minOccurs="0"></element>
	    	<element name="sleepAfter" type="integer"  maxOccurs="1" minOccurs="0"></element>
	    	<element name="scrollX" type="integer"  maxOccurs="1" minOccurs="0"></element>
	    	<element name="scrollY" type="integer"  maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

     <complexType name="Element">
    	<sequence>
    		<element name="finds" type="tns:Finds"></element>
    		<element name="storeValue" type="tns:StoreValue" minOccurs="0"></element>
    		<element name="setValue" type="tns:SetValue" minOccurs="0"></element>
    		<element name="sendKeys" type="tns:SendKeys"
    			minOccurs="0">
    		</element>
    		<element name="click" type="boolean" default="true"
    			minOccurs="0">
    		</element>
    		<element name="moveX" type="int"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="element" type="tns:Element"/>
    		<element name="changeState" type="tns:WaitFor"/>
    		<element name="checkTextEquals" type="tns:CheckEqualsToString" minOccurs="0"></element>
    		<element name="store" type="tns:Store" minOccurs="0"></element>
    	</sequence>
    	<attribute name="checkNullElement" type="boolean" default="false"/>
    </complexType>

    <complexType name="Finds">
    	<choice>
    		<element name="find" type="tns:Find"></element>
    		<element name="waitFor" type="tns:WaitFor"></element>
    	</choice>
    </complexType>
 
    <complexType name="Find">
	    	<choice maxOccurs="1" minOccurs="1">
	    		<element name="byId" type="tns:ById"></element>
	    		<element name="byName" type="tns:ByName"></element>
	    		<element name="byLinkText" type="tns:ByLinkText"></element>
	    		<element name="byXPath" type="tns:ByXPath"></element>
	    		<element name="byCssSelector" type="tns:ByCSSSelector"></element>
	    	</choice>
    	<attribute name="catchException" default="false" type="boolean"/>
    </complexType>

    <complexType name="ById">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ByLinkText">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ByName">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="WaitFor">
    	<choice maxOccurs="1" minOccurs="1">
	    		<element name="byId" type="tns:ById"></element>
	    		<element name="byName" type="tns:ByName"></element>
	    		<element name="byLinkText" type="tns:ByLinkText"></element>
	    		<element name="byXPath" type="tns:ByXPath"></element>
	    		<element name="byCssSelector" type="tns:ByCSSSelector"></element>
    	</choice>
    	<attribute name="catchException" default="false" type="boolean"/>
    </complexType>

    <complexType name="SwitchTo">
    	<choice maxOccurs="1" minOccurs="1">
    		<element name="frame" type="tns:Frame"></element>
    		<element name="alert" type="tns:Alert"></element>
    	</choice>
    </complexType>

    <complexType name="Frame">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Alert">
    	<sequence>
    		<element name="accept" type="boolean"></element>
    	</sequence>
    </complexType>

    <complexType name="ByXPath">
    	<choice>
    		<element name="value" type="string"/>
    		<element name="indexedValue" type="string"/>
    	</choice>
    </complexType>

    <complexType name="ByCSSSelector">
    	<sequence>
    		<element name="value" type="string"/>
    	</sequence>
    </complexType>

    <complexType name="SendKeys">
    	<sequence>
    		<element name="value" type="string"></element>
    		<element name="removeOld" type="boolean"></element>
    		<element name="pressEnter" type="boolean"></element>
    	</sequence>
    </complexType>

    <complexType name="Click"></complexType>
    
     <complexType name="Store">
     	<sequence>
     		<element name="key" type="string" minOccurs="1" maxOccurs="1" />
     	</sequence>
     </complexType>
     
     <complexType name="StoreValue">
     	<sequence>
     		<element name="key" type="string" minOccurs="1" maxOccurs="1" />
     	</sequence>
     </complexType>

     <complexType name="SetValue">
     	<sequence>
     		<element name="keys" type="tns:Values" minOccurs="1" maxOccurs="1" />
     		<element name="valueExpression" type="string" minOccurs="1" maxOccurs="1"/>
     	</sequence>
     </complexType>

     <complexType name="Values">
     	<sequence>
     		<element name="key" type="string" minOccurs="1" maxOccurs="2" />
     	</sequence>
     </complexType>

     <complexType name="Load">
     	<sequence>
     		<element name="key" type="string" minOccurs="1" maxOccurs="1" />
     	</sequence>
     </complexType>

    <complexType name="Select">
    	<sequence>
    		<element name="finds" type="tns:Finds"></element>
    		<element name="selectBy" type="tns:SelectBy"></element>
    	</sequence>
    </complexType>

    <complexType name="PrettySelect">
    	<sequence>
    		<element name="finds" type="tns:Finds"></element>
    		<element name="selectBy" type="tns:PrettySelectBy"></element>
    	</sequence>
    </complexType>

     <complexType name="SelectBy">
    	<choice>
    		<element name="byVisibleText" type="string"></element>
    		<element name="byIndex" type="tns:Index"></element>
    	</choice>
    </complexType>
 
    <complexType name="PrettySelectBy">
    	<sequence>
    		<choice>
    			<element name="byVisibleText" type="string"></element>
    			<element name="byIndex" type="tns:Index"></element>
    		</choice>
    		<element name="arrowArea" type="tns:Finds" minOccurs="1" maxOccurs="1"/>
    		<element name="scrollArea" type="tns:Finds" minOccurs="1" maxOccurs="1"/>
    		<element name="optionsTag" type="string" minOccurs="1" maxOccurs="1"/>
    		<element name="optionsClasses" type="string" minOccurs="1" maxOccurs="1"/>
    	</sequence>
    </complexType>

	<complexType name="Index">
    	<choice>
    		<element name="next" type="boolean"></element>
    		<element name="previous" type="boolean"></element>
    		<element name="middle" type="tns:Middle"></element>
    		<element name="first" type="boolean"></element>
			<element name="last" type="boolean"></element>
    	</choice>
    </complexType>
    
    <complexType name="Middle">
    	<sequence>
			<element name="round" type="tns:Round" minOccurs="1" maxOccurs="1"/>
    	</sequence>
   	</complexType>
    
	<complexType name="Round">
    	<choice>
    		<element name="up" type="boolean"></element>
    		<element name="down" type="boolean"></element>
    		<element name="no" type="boolean"></element>
    	</choice>
    </complexType>

    <complexType name="CheckEqualsToString">
    	<sequence>
    		<element name="value" type="string"></element>
    	</sequence>
    </complexType>

</schema>

=== nickyminch/xmlium/src/test/resources/com/example/test/deleteAllAvailablePortfolios.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:test xmlns:tns="http://www.xmlium.org/TestCase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xmlium.org/TestCase src/main/xsd/TestCase.xsd">

	<tns:repeat>
		<tns:repeatCount>-1</tns:repeatCount>
		<tns:repeatSteps>
			<tns:steps>
				<tns:step>
					<tns:scrollX>0</tns:scrollX>
					<tns:scrollY>0</tns:scrollY>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//a[@id='portfolio-name-form:deletePortfolio']
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:scrollX>0</tns:scrollX>
					<tns:scrollY>0</tns:scrollY>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//a[@id='portfolio-name-form:deletePortfolio']
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
						<tns:click />
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//button[@id='confirmDeletePortfolioDialogForm:noButton']
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
						<tns:click />
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//div[@id='confirmDeletePortfolioDialog' and
										contains(@style,'display: none;')]
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:scrollX>0</tns:scrollX>
					<tns:scrollY>0</tns:scrollY>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//a[@id='portfolio-name-form:deletePortfolio']
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
						<tns:click />
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//button[@id='confirmDeletePortfolioDialogForm:yesButton']
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
						<tns:click />
					</tns:element>
				</tns:step>

				<tns:step>
					<tns:element>
						<tns:finds>
							<tns:waitFor>
								<tns:byXPath>
									<tns:value>//div[@id='confirmDeletePortfolioDialog' and
										contains(@style,'display: none;')]
									</tns:value>
								</tns:byXPath>
							</tns:waitFor>
						</tns:finds>
					</tns:element>
				</tns:step>
			</tns:steps>
		</tns:repeatSteps>
	</tns:repeat>
</tns:test>

=== nickyminch/xmlium/src/test/resources/com/example/test/testKOM56.xml
<?xml version="1.0" encoding="UTF-8"?>
<t:test xmlns:t="http://www.xmlium.org/TestCase"
		xmlns:tns="http://www.xmlium.org/TestSteps"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xmlium.org http://www.xmlium.org/TestCase.xsd">
	<t:testSteps>
		<tns:steps>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Neues Portfolio']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Neues Portfolio']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//input[@id='portfolio-form:portfolioName']
								</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:sendKeys>
						<tns:value>Test KOM-56 from Selenium Tests</tns:value>
					</tns:sendKeys>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//input[@id='portfolio-form:currency-amount']
								</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:sendKeys>
						<tns:value>4000</tns:value>
					</tns:sendKeys>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//span[.='Speichern']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage')]</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage') and contains(text(), 'Ihr Portfolio wurde erfolgreich gespeichert')]</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//button[@id='portfolio-form:back']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-form:ChartDT:0:portfolioPositionDetail']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-form:ChartDT:0:portfolioPositionDetail']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//span[.='Speichern']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage')]</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage') and
									contains(text(), 'Die Portfolio-Position wurde erfolgreich
									gespeichert.')]
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<!-- tns:step> <tns:element> <tns:finds> <tns:waitFor> <tns:byXPath> <tns:value>//label[@id='portfoliodetail-form:requiredInvestment']/parent::td/following-sibling::td[1][text()='0.00']</tns:value> 
				</tns:byXPath> </tns:waitFor> </tns:finds> </tns:element> </tns:step -->

			<tns:step>
				<tns:sleepAfter>200</tns:sleepAfter>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//span[.='Speichern']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage')]</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage') and
									contains(text(), 'Die Portfolio-Position wurde erfolgreich
									gespeichert.')]
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//button[@id='portfoliodetail-form:back']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//button[@id='portfoliodetail-form:back']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:scrollX>0</tns:scrollX>
				<tns:scrollY>0</tns:scrollY>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-name-form:deletePortfolio']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:scrollX>0</tns:scrollX>
				<tns:scrollY>0</tns:scrollY>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-name-form:deletePortfolio']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//button[@id='confirmDeletePortfolioDialogForm:yesButton']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//div[@id='confirmDeletePortfolioDialog' and
									contains(@style,'display: none;')]
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>
		</tns:steps>
	</t:testSteps>
</t:test>

=== nickyminch/xmlium/src/test/resources/com/example/test/base/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test [
<!ENTITY user  "someuser">
<!ENTITY password  "somepassword">
]>
<tns:test xmlns:tns="http://www.xmlium.org/TestCase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xmlium.org/TestCase src/main/xsd/TestCase.xsd">
	<tns:testSteps>
		<tns:steps>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Zur Anmeldung']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//input[@id='login:login-email-text']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:sendKeys>
						<tns:value>&user;</tns:value>
					</tns:sendKeys>
				</tns:element>
			</tns:step>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//input[@id='login:login-password-text']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:sendKeys>
						<tns:value>&password;</tns:value>
					</tns:sendKeys>
				</tns:element>
			</tns:step>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:find>
							<tns:byXPath>
								<tns:value>//span[.='Anmelden']</tns:value>
							</tns:byXPath>
						</tns:find>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>
		</tns:steps>
	</tns:testSteps>
</tns:test>

=== nickyminch/xmlium/src/test/resources/com/example/test/positionDetailsTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<t:test xmlns:t="http://www.xmlium.org/TestCase"
		xmlns:tns="http://www.xmlium.org/TestSteps"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xmlium.org http://www.xmlium.org/TestCase.xsd">
	<t:testSteps>
		<tns:steps>
			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-form:ChartDT:0:portfolioPositionDetail']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//a[@id='portfolio-form:ChartDT:0:portfolioPositionDetail']
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element checkNullElement="true">
					<tns:finds>
						<tns:waitFor catchException="true">
							<tns:byXPath>
								<tns:indexedValue>//div[contains(@id,
									'portfoliodetail-form:etfDataTable:index:${first}')]/descendant::span[contains(@class,'ui-chkbox-icon
									ui-icon ui-icon-blank ui-c')]
								</tns:indexedValue>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element checkNullElement="true">
					<tns:finds>
						<tns:waitFor catchException="true">
							<tns:byXPath>
								<tns:indexedValue>//div[contains(@id,
									'portfoliodetail-form:etfDataTable:index:${next}')]/descendant::span[contains(@class,'ui-chkbox-icon
									ui-icon ui-icon-blank ui-c')]
								</tns:indexedValue>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element checkNullElement="true">
					<tns:finds>
						<tns:waitFor catchException="true">
							<tns:byXPath>
								<tns:indexedValue>//div[contains(@id,
									'portfoliodetail-form:etfDataTable:index:${next}')]/descendant::span[contains(@class,'ui-chkbox-icon
									ui-icon ui-icon-blank ui-c')]
								</tns:indexedValue>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Speichern']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Speichern']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage')]</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//li[contains(@class,'infoMessage') and
									contains(text(), 'Die Portfolio-Position wurde erfolgreich
									gespeichert.')]
								</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
				</tns:element>
			</tns:step>

			<tns:step>
				<tns:element>
					<tns:finds>
						<tns:waitFor>
							<tns:byXPath>
								<tns:value>//span[.='Zur√ºck']</tns:value>
							</tns:byXPath>
						</tns:waitFor>
					</tns:finds>
					<tns:click />
				</tns:element>
			</tns:step>
		</tns:steps>
	</t:testSteps>
</t:test>
